"""Ansicht 0.6.6, aus solartracker_ui_design1.py des Benutzers abgeleitet.
Demo-Logik entfernt; reale Aktionen implementiert bedienfeld_qt.py.
"""
import sys
from datetime import datetime
from PySide6.QtCore import Qt, QTimer, Signal
from PySide6.QtGui import QColor, QFont, QPainter, QPen
from PySide6.QtWidgets import QApplication, QButtonGroup, QComboBox, QDoubleSpinBox, QFrame, QGridLayout, QHBoxLayout, QLabel, QLineEdit, QMainWindow, QMessageBox, QPushButton, QRadioButton, QSpinBox, QStackedWidget, QVBoxLayout, QWidget
AZ_MIN = 0.0
AZ_MAX = 180.0
EL_MIN = 0.0
EL_MAX = 90.0
BACKOFF_DEG = 10.0
STEP_DEG = 10.0

class AxisGauge(QWidget):
    """Einfache grafische Achsanzeige."""

    def __init__(self, title, minimum, maximum, accent='#3aa6ff', parent=None):
        super().__init__(parent)
        self.title = title
        self.minimum = minimum
        self.maximum = maximum
        self.value = None
        self.accent = QColor(accent)
        self.setMinimumHeight(140)

    def set_value(self, value):
        self.value = None if value is None else max(self.minimum, min(self.maximum, float(value)))
        self.update()

    def paintEvent(self, event):
        p = QPainter(self)
        p.setRenderHint(QPainter.Antialiasing)
        w = self.width()
        h = self.height()
        p.setPen(QColor('#d8e2ef'))
        p.setFont(QFont('Segoe UI', 11, QFont.Bold))
        p.drawText(12, 24, self.title)
        x0, x1 = (22, w - 22)
        y = h - 45
        p.setPen(QPen(QColor('#526273'), 3))
        p.drawLine(x0, y, x1, y)
        p.setFont(QFont('Segoe UI', 8))
        for i in range(6):
            x = x0 + (x1 - x0) * i / 5
            p.setPen(QPen(QColor('#526273'), 1))
            p.drawLine(int(x), y - 7, int(x), y + 7)
            val = self.minimum + (self.maximum - self.minimum) * i / 5
            p.setPen(QColor('#97a8bb'))
            p.drawText(int(x - 16), y + 24, 40, 15, Qt.AlignCenter, f'{val:.0f}°')
        if self.value is None:
            p.setPen(QColor('#97a8bb'))
            p.setFont(QFont('Segoe UI', 13))
            p.drawText(10, 35, w - 20, 40, Qt.AlignCenter, 'Position unbekannt')
            return
        ratio = (self.value - self.minimum) / max(1e-09, self.maximum - self.minimum)
        x = x0 + (x1 - x0) * ratio
        p.setPen(Qt.NoPen)
        p.setBrush(self.accent)
        p.drawEllipse(int(x - 8), int(y - 8), 16, 16)
        p.setPen(self.accent)
        p.setFont(QFont('Segoe UI', 22, QFont.Bold))
        p.drawText(10, 35, w - 20, 40, Qt.AlignCenter, f'{self.value:.1f}°')

class DesignFenster(QMainWindow):

    def __init__(self):
        super().__init__()
        self.resize(1450, 900)
        self.build_ui()
        self.apply_style()

    def build_ui(self):
        root = QWidget()
        self.setCentralWidget(root)
        main = QHBoxLayout(root)
        main.setContentsMargins(0, 0, 0, 0)
        main.setSpacing(0)
        nav = QFrame()
        nav.setObjectName('nav')
        nav.setFixedWidth(240)
        nav_layout = QVBoxLayout(nav)
        nav_layout.setContentsMargins(20, 25, 20, 25)
        nav_layout.setSpacing(12)
        logo = QLabel('SOLAR\nTRACKER')
        logo.setObjectName('logo')
        nav_layout.addWidget(logo)
        sub = QLabel('PC BEDIENPANEL')
        sub.setObjectName('muted')
        nav_layout.addWidget(sub)
        nav_layout.addSpacing(25)
        self.nav_group = QButtonGroup(self)
        self.nav_group.setExclusive(True)
        self.btn_oper = self.make_nav_button('☀  Betrieb')
        self.btn_sim = self.make_nav_button('▶  Simulation')
        self.btn_settings = self.make_nav_button('⚙  Einstellungen')
        self.btn_test = self.make_nav_button('🧪  Komponententest')
        for i, btn in enumerate([self.btn_oper, self.btn_sim, self.btn_settings, self.btn_test]):
            self.nav_group.addButton(btn, i)
            nav_layout.addWidget(btn)
            btn.clicked.connect(lambda checked=False, index=i: self.pages.setCurrentIndex(index))
        nav_layout.addStretch()
        hint = QLabel('Design 1\nPC-Steuerung 0.6.6')
        hint.setObjectName('muted')
        nav_layout.addWidget(hint)
        main.addWidget(nav)
        center = QFrame()
        center.setObjectName('center')
        center_layout = QVBoxLayout(center)
        center_layout.setContentsMargins(26, 22, 26, 22)
        center_layout.setSpacing(18)
        center_layout.addWidget(self.build_topbar())
        self.pages = QStackedWidget()
        self.pages.addWidget(self.page_operation())
        self.pages.addWidget(self.page_simulation())
        self.pages.addWidget(self.page_settings())
        self.pages.addWidget(self.page_component_test())
        center_layout.addWidget(self.pages, 1)
        main.addWidget(center, 1)
        right = self.build_right_status()
        right.setFixedWidth(300)
        main.addWidget(right)
        self.btn_oper.setChecked(True)

    def make_nav_button(self, text):
        btn = QPushButton(text)
        btn.setCheckable(True)
        btn.setCursor(Qt.PointingHandCursor)
        btn.setMinimumHeight(52)
        return btn

    def build_topbar(self):
        frame = QFrame()
        frame.setObjectName('card')
        lay = QHBoxLayout(frame)
        lay.setContentsMargins(18, 12, 18, 12)
        title = QLabel('SolarTracker Steuerzentrale')
        title.setObjectName('h2')
        lay.addWidget(title)
        lay.addStretch()
        self.port_combo = QComboBox()
        self.port_combo.setEditable(True)
        self.port_combo.addItem('COM3')
        self.port_combo.setFixedWidth(110)
        lay.addWidget(self.port_combo)
        self.connect_btn = QPushButton('Verbindung herstellen')
        self.connect_btn.setObjectName('primary')
        self.connect_btn.clicked.connect(self.toggle_connection)
        lay.addWidget(self.connect_btn)
        self.connection_label = QLabel('● getrennt')
        self.connection_label.setObjectName('dangerText')
        lay.addWidget(self.connection_label)
        return frame

    def page_operation(self):
        page = QWidget()
        layout = QVBoxLayout(page)
        layout.setSpacing(18)
        header = QLabel('Betrieb')
        header.setObjectName('h1')
        layout.addWidget(header)
        grid = QGridLayout()
        grid.setHorizontalSpacing(18)
        grid.setVerticalSpacing(18)
        status_card = self.card()
        sl = QVBoxLayout(status_card)
        sl.addWidget(self.section_title('Status'))
        self.operation_status = QLabel('Betrieb nicht aktiv')
        self.operation_status.setObjectName('bigStatus')
        sl.addWidget(self.operation_status)
        self.operation_info = QLabel('Die Echtzeit-Nachführung wird später mit dem ESP32 verbunden.\nIn dieser Demo werden nur Oberfläche und Zustände getestet.')
        self.operation_info.setWordWrap(True)
        self.operation_info.setObjectName('muted')
        sl.addWidget(self.operation_info)
        self.operation_btn = QPushButton('Betrieb aktivieren')
        self.operation_btn.setObjectName('success')
        self.operation_btn.setMinimumHeight(52)
        self.operation_btn.clicked.connect(self.toggle_operation)
        sl.addWidget(self.operation_btn)
        grid.addWidget(status_card, 0, 0)
        values = self.card()
        vl = QVBoxLayout(values)
        vl.addWidget(self.section_title('Live-Werte'))
        self.oper_time = QLabel('--:--:--')
        self.oper_time.setObjectName('value')
        self.oper_az = QLabel('Azimut: 0.0°')
        self.oper_el = QLabel('Elevation: 0.0°')
        self.oper_az.setObjectName('accentAz')
        self.oper_el.setObjectName('accentEl')
        vl.addWidget(self.oper_time)
        vl.addWidget(self.oper_az)
        vl.addWidget(self.oper_el)
        vl.addStretch()
        grid.addWidget(values, 0, 1)
        layout.addLayout(grid)
        layout.addStretch()
        return page

    def page_simulation(self):
        page = QWidget()
        layout = QVBoxLayout(page)
        layout.setSpacing(18)
        header = QLabel('Simulation')
        header.setObjectName('h1')
        layout.addWidget(header)
        card = self.card()
        cl = QVBoxLayout(card)
        cl.addWidget(self.section_title('Simulationsstufe auswählen'))
        row = QHBoxLayout()
        self.sim_buttons = []
        for label, sec in [('Stufe 1\n30 Sekunden', 30), ('Stufe 2\n60 Sekunden', 60), ('Stufe 3\n120 Sekunden', 120)]:
            b = QPushButton(label)
            b.setMinimumHeight(72)
            b.clicked.connect(lambda checked=False, s=sec: self.start_simulation(s))
            row.addWidget(b)
            self.sim_buttons.append(b)
        cl.addLayout(row)
        self.sim_status = QLabel('Simulation bereit')
        self.sim_status.setObjectName('bigStatus')
        cl.addWidget(self.sim_status)
        self.sim_progress = QLabel('Tagesverlauf: 0 %')
        self.sim_progress.setObjectName('muted')
        cl.addWidget(self.sim_progress)
        stop = QPushButton('Simulation stoppen')
        stop.setObjectName('danger')
        stop.clicked.connect(self.stop_simulation)
        cl.addWidget(stop)
        layout.addWidget(card)
        info = self.card()
        il = QVBoxLayout(info)
        il.addWidget(self.section_title('Funktion'))
        t = QLabel('Die Simulation bildet einen kompletten Sonnentag ab. Azimut und Elevation werden dabei live auf der rechten Seite dargestellt. Später werden dieselben Sollpositionen zusätzlich an die Motoren übertragen.')
        t.setWordWrap(True)
        il.addWidget(t)
        layout.addWidget(info)
        layout.addStretch()
        return page

    def page_settings(self):
        page = QWidget()
        layout = QVBoxLayout(page)
        layout.setSpacing(18)
        header = QLabel('Einstellungen & manuelle Achssteuerung')
        header.setObjectName('h1')
        layout.addWidget(header)
        top = QHBoxLayout()
        control = self.card()
        ctl = QVBoxLayout(control)
        ctl.addWidget(self.section_title('Manuelle Steuerung'))
        modes = QHBoxLayout()
        self.radio_step = QRadioButton('Schrittmodus 10°')
        self.radio_hold = QRadioButton('Haltemodus')
        self.radio_step.setChecked(True)
        modes.addWidget(self.radio_step)
        modes.addWidget(self.radio_hold)
        ctl.addLayout(modes)
        pad = QGridLayout()
        self.btn_up = QPushButton('▲\nOBEN')
        self.btn_left = QPushButton('◀ LINKS')
        self.btn_enter = QPushButton('ENTER')
        self.btn_right = QPushButton('RECHTS ▶')
        self.btn_down = QPushButton('UNTEN\n▼')
        for b in [self.btn_up, self.btn_left, self.btn_enter, self.btn_right, self.btn_down]:
            b.setMinimumSize(115, 70)
        pad.addWidget(self.btn_up, 0, 1)
        pad.addWidget(self.btn_left, 1, 0)
        pad.addWidget(self.btn_enter, 1, 1)
        pad.addWidget(self.btn_right, 1, 2)
        pad.addWidget(self.btn_down, 2, 1)
        ctl.addLayout(pad)
        self.bind_direction_button(self.btn_right, 'az', +1)
        self.bind_direction_button(self.btn_left, 'az', -1)
        self.bind_direction_button(self.btn_up, 'el', +1)
        self.bind_direction_button(self.btn_down, 'el', -1)
        self.btn_enter.clicked.connect(lambda: self.flash_message('ENTER bestätigt'))
        note = QLabel('Schrittmodus: 10° pro Tastendruck.\nHaltemodus: konstante Bewegung, solange die Taste gehalten wird.\nEndschalter: bei Erreichen automatisch 10° zurück zum Entlasten.')
        note.setWordWrap(True)
        note.setObjectName('muted')
        ctl.addWidget(note)
        top.addWidget(control, 2)
        settings = self.card()
        st = QVBoxLayout(settings)
        st.addWidget(self.section_title('Zeit & Standort'))
        self.time_edit = QLineEdit(datetime.now().strftime('%H:%M:%S'))
        self.date_edit = QLineEdit(datetime.now().strftime('%d.%m.%Y'))
        self.lat = QDoubleSpinBox()
        self.lat.setRange(-90.0, 90.0)
        self.lat.setDecimals(6)
        self.lat.setValue(50.1109)
        self.lon = QDoubleSpinBox()
        self.lon.setRange(-180.0, 180.0)
        self.lon.setDecimals(6)
        self.lon.setValue(8.6821)
        self.lang = QComboBox()
        self.lang.addItems(['Deutsch'])
        form = QGridLayout()
        form.addWidget(QLabel('Datum'), 0, 0)
        form.addWidget(self.date_edit, 0, 1)
        form.addWidget(QLabel('Uhrzeit'), 1, 0)
        form.addWidget(self.time_edit, 1, 1)
        form.addWidget(QLabel('Breitengrad'), 2, 0)
        form.addWidget(self.lat, 2, 1)
        form.addWidget(QLabel('Längengrad'), 3, 0)
        form.addWidget(self.lon, 3, 1)
        self.land = QLineEdit()
        self.land.setPlaceholderText('z. B. Deutschland')
        self.stadt = QLineEdit()
        self.stadt.setPlaceholderText('z. B. Bad Vilbel')
        form.addWidget(QLabel('Land'), 4, 0)
        form.addWidget(self.land, 4, 1)
        form.addWidget(QLabel('Stadt'), 5, 0)
        form.addWidget(self.stadt, 5, 1)
        form.addWidget(QLabel('Sprache'), 6, 0)
        form.addWidget(self.lang, 6, 1)
        st.addLayout(form)
        save = QPushButton('Einstellungen übernehmen')
        save.setObjectName('primary')
        save.clicked.connect(self.save_settings)
        st.addWidget(save)
        st.addStretch()
        top.addWidget(settings, 1)
        layout.addLayout(top)
        return page

    def page_component_test(self):
        page = QWidget()
        layout = QVBoxLayout(page)
        layout.setSpacing(18)
        header = QLabel('Komponententest')
        header.setObjectName('h1')
        layout.addWidget(header)
        desc = QLabel('Jede Komponente kann hier unabhängig vom normalen Betriebsprogramm getestet werden.')
        desc.setWordWrap(True)
        desc.setObjectName('muted')
        layout.addWidget(desc)
        self.test_stack = QStackedWidget()
        selector = self.card()
        sl = QVBoxLayout(selector)
        sl.addWidget(self.section_title('Komponente auswählen'))
        grid = QGridLayout()
        tests = [('Azimut-Motor', 1), ('Elevations-Motor', 2), ('Endschalter', 3), ('RTC DS3231', 4), ('LCD 16x2', 5), ('Bedientasten', 6)]
        for i, (name, idx) in enumerate(tests):
            b = QPushButton(name)
            b.setMinimumHeight(60)
            b.clicked.connect(lambda checked=False, x=idx: self.test_stack.setCurrentIndex(x))
            grid.addWidget(b, i // 3, i % 3)
        sl.addLayout(grid)
        self.test_stack.addWidget(selector)
        self.test_stack.addWidget(self.motor_test_page('Azimut-Motor', 'az'))
        self.test_stack.addWidget(self.motor_test_page('Elevations-Motor', 'el'))
        self.test_stack.addWidget(self.endstop_test_page())
        self.test_stack.addWidget(self.rtc_test_page())
        self.test_stack.addWidget(self.lcd_test_page())
        self.test_stack.addWidget(self.button_test_page())
        layout.addWidget(self.test_stack, 1)
        return page

    def motor_test_page(self, title, axis):
        page = self.card()
        l = QVBoxLayout(page)
        l.addWidget(self.section_title(title))
        value = QLabel('Richtungstest: 5 Grad pro Klick')
        value.setObjectName('bigStatus')
        l.addWidget(value)
        row = QHBoxLayout()
        minus = QPushButton('Rückwärts')
        plus = QPushButton('Vorwärts')
        stop = QPushButton('STOP')
        stop.setObjectName('danger')
        row.addWidget(minus)
        row.addWidget(stop)
        row.addWidget(plus)
        l.addLayout(row)
        minus.clicked.connect(lambda: self.move_axis(axis, -1, 5, test=True))
        plus.clicked.connect(lambda: self.move_axis(axis, +1, 5, test=True))
        stop.clicked.connect(self.stop_all)
        back = QPushButton('← Zur Komponentenauswahl')
        back.clicked.connect(lambda: self.test_stack.setCurrentIndex(0))
        l.addWidget(back)
        l.addStretch()
        return page

    def endstop_test_page(self):
        page = self.card()
        l = QVBoxLayout(page)
        l.addWidget(self.section_title('Endschalter-Test'))
        self.end_labels = {}
        for key, text in [('az_min', 'Azimut MIN'), ('az_max', 'Azimut MAX'), ('el_min', 'Elevation MIN'), ('el_max', 'Elevation MAX')]:
            row = QHBoxLayout()
            lab = QLabel(f'{text}: FREI')
            lab.setObjectName('successText')
            btn = QPushButton('Schalter antippen')
            btn.clicked.connect(lambda checked=False, k=key, la=lab, tx=text: self.fake_endstop(k, la, tx))
            row.addWidget(lab)
            row.addStretch()
            row.addWidget(btn)
            l.addLayout(row)
            self.end_labels[key] = lab
        back = QPushButton('← Zur Komponentenauswahl')
        back.clicked.connect(lambda: self.test_stack.setCurrentIndex(0))
        l.addWidget(back)
        l.addStretch()
        return page

    def rtc_test_page(self):
        page = self.card()
        l = QVBoxLayout(page)
        l.addWidget(self.section_title('RTC DS3231 Test'))
        self.rtc_value = QLabel('Noch nicht ausgelesen')
        self.rtc_value.setObjectName('value')
        l.addWidget(self.rtc_value)
        b = QPushButton('RTC auslesen')
        b.clicked.connect(self.read_rtc)
        l.addWidget(b)
        note = QLabel('Demo: aktuell wird die PC-Systemzeit verwendet. Später wird der DS3231 über den ESP32 ausgelesen.')
        note.setWordWrap(True)
        note.setObjectName('muted')
        l.addWidget(note)
        back = QPushButton('← Zur Komponentenauswahl')
        back.clicked.connect(lambda: self.test_stack.setCurrentIndex(0))
        l.addWidget(back)
        l.addStretch()
        return page

    def lcd_test_page(self):
        page = self.card()
        l = QVBoxLayout(page)
        l.addWidget(self.section_title('LCD 16x2 Test'))
        self.lcd_line1 = QLineEdit('SolarTracker')
        self.lcd_line2 = QLineEdit('LCD Test OK')
        self.lcd_preview = QLabel('SolarTracker\nLCD Test OK')
        self.lcd_preview.setObjectName('lcd')
        self.lcd_preview.setAlignment(Qt.AlignCenter)
        self.lcd_preview.setMinimumHeight(95)
        l.addWidget(QLabel('Zeile 1'))
        l.addWidget(self.lcd_line1)
        l.addWidget(QLabel('Zeile 2'))
        l.addWidget(self.lcd_line2)
        l.addWidget(self.lcd_preview)
        send = QPushButton('Text ans LCD senden')
        send.clicked.connect(self.lcd_preview_only)
        l.addWidget(send)
        back = QPushButton('← Zur Komponentenauswahl')
        back.clicked.connect(lambda: self.test_stack.setCurrentIndex(0))
        l.addWidget(back)
        l.addStretch()
        return page

    def button_test_page(self):
        page = self.card()
        l = QVBoxLayout(page)
        l.addWidget(self.section_title('Bedientasten-Test'))
        self.button_test_value = QLabel('Noch keine Taste gedrückt')
        self.button_test_value.setObjectName('bigStatus')
        l.addWidget(self.button_test_value)
        grid = QGridLayout()
        for text, r, c in [('OBEN', 0, 1), ('LINKS', 1, 0), ('ENTER', 1, 1), ('RECHTS', 1, 2), ('UNTEN', 2, 1)]:
            b = QPushButton(text)
            b.setMinimumHeight(55)
            b.clicked.connect(lambda checked=False, t=text: self.button_test_value.setText(f'Taste erkannt: {t}'))
            grid.addWidget(b, r, c)
        l.addLayout(grid)
        back = QPushButton('← Zur Komponentenauswahl')
        back.clicked.connect(lambda: self.test_stack.setCurrentIndex(0))
        l.addWidget(back)
        l.addStretch()
        return page

    def build_right_status(self):
        frame = QFrame()
        frame.setObjectName('rightpanel')
        layout = QVBoxLayout(frame)
        layout.setContentsMargins(18, 22, 18, 22)
        layout.setSpacing(14)
        title = QLabel('LIVE POSITION')
        title.setObjectName('h2')
        layout.addWidget(title)
        self.mode_label = QLabel('Modus: Standby')
        self.mode_label.setObjectName('muted')
        layout.addWidget(self.mode_label)
        self.az_gauge = AxisGauge('AZIMUT', AZ_MIN, AZ_MAX, '#3aa6ff')
        self.el_gauge = AxisGauge('ELEVATION', EL_MIN, EL_MAX, '#ffb347')
        layout.addWidget(self.az_gauge)
        layout.addWidget(self.el_gauge)
        pos = self.card()
        pl = QVBoxLayout(pos)
        self.az_value = QLabel('Azimut 90.0°')
        self.el_value = QLabel('Elevation 30.0°')
        self.az_value.setObjectName('accentAz')
        self.el_value.setObjectName('accentEl')
        self.az_value.setFont(QFont('Segoe UI', 15, QFont.Bold))
        self.el_value.setFont(QFont('Segoe UI', 15, QFont.Bold))
        pl.addWidget(self.az_value)
        pl.addWidget(self.el_value)
        self.endstop_status = QLabel('Endschalter: frei')
        self.endstop_status.setObjectName('successText')
        pl.addWidget(self.endstop_status)
        layout.addWidget(pos)
        layout.addStretch()
        return frame

    def card(self):
        f = QFrame()
        f.setObjectName('card')
        return f

    def section_title(self, text):
        l = QLabel(text)
        l.setObjectName('h2')
        return l

    def apply_style(self):
        self.setStyleSheet('\n            QMainWindow, QWidget {\n                background: #0d1117;\n                color: #e7edf5;\n                font-family: "Segoe UI";\n                font-size: 14px;\n            }\n\n            QFrame#nav {\n                background: #111820;\n                border-right: 1px solid #243140;\n            }\n\n            QFrame#center {\n                background: #0d1117;\n            }\n\n            QFrame#rightpanel {\n                background: #111820;\n                border-left: 1px solid #243140;\n            }\n\n            QFrame#card {\n                background: #151d27;\n                border: 1px solid #263546;\n                border-radius: 14px;\n            }\n\n            QLabel#logo {\n                color: #65b7ff;\n                font-size: 25px;\n                font-weight: 800;\n                letter-spacing: 2px;\n            }\n\n            QLabel#h1 {\n                font-size: 26px;\n                font-weight: 800;\n                color: #f4f8fc;\n            }\n\n            QLabel#h2 {\n                font-size: 17px;\n                font-weight: 700;\n                color: #dfe9f5;\n            }\n\n            QLabel#muted {\n                color: #8fa1b4;\n            }\n\n            QLabel#bigStatus {\n                font-size: 22px;\n                font-weight: 800;\n                color: #ffffff;\n            }\n\n            QLabel#value {\n                font-size: 22px;\n                font-weight: 700;\n                color: #ffffff;\n            }\n\n            QLabel#accentAz {\n                color: #3aa6ff;\n                font-weight: 700;\n            }\n\n            QLabel#accentEl {\n                color: #ffb347;\n                font-weight: 700;\n            }\n\n            QLabel#successText {\n                color: #52d273;\n                font-weight: 700;\n            }\n\n            QLabel#dangerText {\n                color: #ff6b6b;\n                font-weight: 700;\n            }\n\n            QLabel#lcd {\n                background: #b7cf8d;\n                color: #1b2a13;\n                border: 4px solid #283327;\n                border-radius: 8px;\n                font-family: Consolas;\n                font-size: 20px;\n                font-weight: 700;\n                padding: 10px;\n            }\n\n            QPushButton {\n                background: #1b2734;\n                color: #eaf2fa;\n                border: 1px solid #31445a;\n                border-radius: 9px;\n                padding: 10px 14px;\n                font-weight: 600;\n            }\n\n            QPushButton:hover {\n                background: #25364a;\n                border-color: #4d6d8f;\n            }\n\n            QPushButton:pressed {\n                background: #101820;\n            }\n\n            QPushButton:checked {\n                background: #1d4d73;\n                border-color: #3aa6ff;\n                color: white;\n            }\n\n            QPushButton#primary {\n                background: #1769aa;\n                border-color: #318cd1;\n            }\n\n            QPushButton#success {\n                background: #1f7a43;\n                border-color: #39a960;\n            }\n\n            QPushButton#danger {\n                background: #8d2d35;\n                border-color: #c14b55;\n            }\n\n            QComboBox, QLineEdit, QDoubleSpinBox, QSpinBox {\n                background: #0f1620;\n                color: #edf4fb;\n                border: 1px solid #31445a;\n                border-radius: 8px;\n                padding: 8px;\n                min-height: 24px;\n            }\n\n            QRadioButton {\n                spacing: 7px;\n            }\n\n            QStatusBar {\n                background: #101720;\n                color: #9fb2c6;\n            }\n        ')
